import type {Metadata} from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "audiophile-ecommerce",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="">
        
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          
        </footer>
      </body>
    </html>
  );
}
